backend:
  name: github
  repo: lucasmarques73/gatsby-blog
  branch: master
  site_domain: lucasmarques-blog.netlify.app

media_folder: static/assets/img
public_folder: /assets/img
publish_mode: editorial_workflow

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Type", name: "type", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD hh:mm:ss",
        }
      - { label: "image", name: "image", widget: "image" }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          options: ["js", "php", "go", "Dev", "react", "devops", "misc"],
        }
      - { label: "Tags", name: "tags", widget: "list", default: [""] }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "projects"
    label: "Projects"
    folder: "projects"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Type", name: "type", widget: "hidden", default: "page" }
      - {
          label: "Category",
          name: "category",
          widget: "hidden",
          default: "projetos",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    files:
      - file: "pages/about.md"
        label: "About"
        name: "about"
        create: true
        fields:
          - { label: "Type", name: "type", widget: "hidden", default: "page" }
          - {
              label: "Category",
              name: "category",
              widget: "hidden",
              default: "sobre",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
